[project]
name = "chile-dtpm-gtfs"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Eli-ezer Reuven Ramirez Ruiz", email = "ramirez.ruiz.eliezer.reuven@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
chile-dtpm-gtfs = "chile_dtpm_gtfs:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
